declare module 'react-slideshow-image'
declare module 'react-router-dom'
declare module 'list-react-files'
declare module 'react-scroll-to-top'
declare module 'react-lazy-load'
declare module 'react-touch'
