const firstMonthDb = [
    {src: 'first (1).jpg'},
    {src: 'first (2).jpg'},
    {src: 'first (3).jpg'},
    {src: 'first (4).jpg'},
    {src: 'first (5).jpg'},
    {src: 'first (6).jpg'},
    {src: 'first (7).jpg'},
    {src: 'first (8).jpg'},
    {src: 'first (9).jpg'},
    {src: 'first (10).jpg'},
    {src: 'first (12).jpg'},
    {src: 'first (13).jpg'},
    {src: 'first (14).jpg'},
    {src: 'first (15).jpg'},
    {src: 'first (16).jpg'},
    {src: 'first (17).jpg', down: true},
    {src: 'first (18).jpg', down: true},
    {src: 'first (19).jpg', down: true},
    {src: 'first (20).jpg', down: true},
    {src: 'first (21).jpg', down: true},
    {src: 'first (22).jpg', down: true},
    {src: 'first (23).jpg', down: true},
    {src: 'first (24).jpg', down: true},
]

export default firstMonthDb