const firstMonthDb = [
    {src: 'first (1).webp'},
    {src: 'first (23).webp'},
    {src: 'first (2).webp'},
    {src: 'first (18).webp'},
    {src: 'first (3).webp'},
    {src: 'first (15).webp'},
    {src: 'first (4).webp'},
    {src: 'first (5).webp'},
    {src: 'first (22).webp'},
    {src: 'first (6).webp'},
    {src: 'first (19).webp'},
    {src: 'first (7).webp'},
    {src: 'first (20).webp'},
    {src: 'first (8).webp'},
    {src: 'first (9).webp'},
    {src: 'first (21).webp'},
    {src: 'first (10).webp'},
    {src: 'first (12).webp'},
    {src: 'first (13).webp'},
    {src: 'first (14).webp'},
    {src: 'first (16).webp'},
    {src: 'first (17).webp'},
    {src: 'first (24).webp'},
]

export default firstMonthDb