const secondMonthDb = [
    {src: 'second (1).webp'},
    {src: 'second (29).webp'},
    {src: 'second (2).webp'},
    {src: 'second (3).webp'},
    {src: 'second (4).webp'},
    {src: 'second (5).webp'},
    {src: 'second (6).webp'},
    {src: 'second (7).webp'},
    {src: 'second (8).webp'},
    {src: 'second (9).webp'},
    {src: 'second (10).webp'},
    {src: 'second (12).webp'},
    {src: 'second (13).webp'},
    {src: 'second (14).webp'},
    {src: 'second (30).webp'},
    {src: 'second (28).webp'},
    {src: 'second (15).webp'},
    {src: 'second (16).webp'},
    {src: 'second (26).webp'},
    {src: 'second (18).webp'},
    {src: 'second (19).webp'},
    {src: 'second (17).webp'},
    {src: 'second (20).webp'},
    {src: 'second (21).webp'},
    {src: 'second (22).webp'},
    {src: 'second (23).webp'},
    {src: 'second (27).webp'},
    {src: 'second (25).webp'},
    {src: 'second (24).webp'},
]

export default secondMonthDb