const secondMonthDb = [
    {src: 'second (1).jpg'},
    {src: 'second (2).jpg'},
    {src: 'second (3).jpg'},
    {src: 'second (4).jpg'},
    {src: 'second (5).jpg'},
    {src: 'second (6).jpg'},
    {src: 'second (7).jpg'},
    {src: 'second (8).jpg'},
    {src: 'second (9).jpg'},
    {src: 'second (10).jpg'},
    {src: 'second (12).jpg'},
    {src: 'second (13).jpg'},
    {src: 'second (14).jpg'},
    {src: 'second (15).jpg'},
    {src: 'second (16).jpg'},
    {src: 'second (17).jpg'},
    {src: 'second (18).jpg'},
    {src: 'second (19).jpg'},
    {src: 'second (20).jpg'},
    {src: 'second (21).jpg'},
    {src: 'second (22).jpg'},
    {src: 'second (23).jpg', down: true},
    {src: 'second (24).jpg', down: true},
    {src: 'second (25).jpg', down: true},
    {src: 'second (26).jpg', down: true},
    {src: 'second (27).jpg', down: true},
    {src: 'second (28).jpg', down: true},
    {src: 'second (29).jpg', down: true},
    {src: 'second (30).jpg', down: true},
]

export default secondMonthDb